[package]
  cjc-version = "1.0.3"
  name = "generators"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = "--experimental --enable-eh"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

# [target.x86_64-unknown-linux-gnu]
  # [target.x86_64-unknown-linux-gnu.bin-dependencies]
    # path-option = ["${CANGJIE_HOME}"]
